version: "3"

services:
  unsplash_db:
    image: mongo:latest
    container_name: unsplash_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

volumes:
  usplash_db:
    driver: local
